import pygame


class Screen(object):
    def __init__(self, mapfile, spritesheet):
        """
        Opens an existing mapfile, or creates a new one if none exists.
        :param mapfile: File name OR integer tuple
        :return: Map object
        """
        # TODO: Find better way to store spritenums list
        spritenums = {0: spritesheet[0][0],
                      1: spritesheet[0][1],
                      2: spritesheet[0][2],
                      3: spritesheet[0][3],
                      4: spritesheet[0][4],
                      5: spritesheet[0][5],
                      6: spritesheet[0][6],
                      7: spritesheet[0][7],
                      8: spritesheet[0][8],
                      9: spritesheet[0][9],
                      10: spritesheet[0][10],
                      11: spritesheet[0][11],
                      12: spritesheet[0][12],
                      13: spritesheet[0][13],
                      14: spritesheet[0][14],
                      15: spritesheet[0][15],
                      16: spritesheet[0][16],
                      17: spritesheet[0][17],
                      18: spritesheet[0][18],
                      19: spritesheet[0][19],
                      20: spritesheet[0][20],
                      21: spritesheet[1][0],
                      22: spritesheet[1][1],
                      23: spritesheet[1][2],
                      24: spritesheet[1][3],
                      25: spritesheet[1][4],
                      26: spritesheet[1][5],
                      27: spritesheet[1][6],
                      28: spritesheet[1][7],
                      29: spritesheet[1][8],
                      30: spritesheet[1][9],
                      31: spritesheet[1][10],
                      32: spritesheet[1][11],
                      33: spritesheet[1][12],
                      34: spritesheet[1][13],
                      35: spritesheet[1][14],
                      36: spritesheet[1][15],
                      37: spritesheet[1][16],
                      38: spritesheet[1][17],
                      39: spritesheet[1][18],
                      40: spritesheet[1][19],
                      41: spritesheet[1][20],
                      42: spritesheet[2][0],
                      43: spritesheet[2][1],
                      44: spritesheet[2][2],
                      45: spritesheet[2][3],
                      46: spritesheet[2][4],
                      47: spritesheet[2][5],
                      48: spritesheet[2][6],
                      49: spritesheet[2][7],
                      50: spritesheet[2][8],
                      51: spritesheet[2][9],
                      52: spritesheet[2][10],
                      53: spritesheet[2][11],
                      54: spritesheet[2][12],
                      55: spritesheet[2][13],
                      56: spritesheet[2][14],
                      57: spritesheet[2][15],
                      58: spritesheet[2][16],
                      59: spritesheet[2][17],
                      60: spritesheet[2][18],
                      61: spritesheet[2][19],
                      62: spritesheet[2][20],
                      63: spritesheet[3][0],
                      64: spritesheet[3][1],
                      65: spritesheet[3][2],
                      66: spritesheet[3][3],
                      67: spritesheet[3][4],
                      68: spritesheet[3][5],
                      69: spritesheet[3][6],
                      70: spritesheet[3][7],
                      71: spritesheet[3][8],
                      72: spritesheet[3][9],
                      73: spritesheet[3][10],
                      74: spritesheet[3][11],
                      75: spritesheet[3][12],
                      76: spritesheet[3][13],
                      77: spritesheet[3][14],
                      78: spritesheet[3][15],
                      79: spritesheet[3][16],
                      80: spritesheet[3][17],
                      81: spritesheet[3][18],
                      82: spritesheet[3][19],
                      83: spritesheet[3][20],
                      84: spritesheet[4][0],
                      85: spritesheet[4][1],
                      86: spritesheet[4][2],
                      87: spritesheet[4][3],
                      88: spritesheet[4][4],
                      89: spritesheet[4][5],
                      90: spritesheet[4][6],
                      91: spritesheet[4][7],
                      92: spritesheet[4][8],
                      93: spritesheet[4][9],
                      94: spritesheet[4][10],
                      95: spritesheet[4][11],
                      96: spritesheet[4][12],
                      97: spritesheet[4][13],
                      98: spritesheet[4][14],
                      99: spritesheet[4][15],
                      100: spritesheet[4][16],
                      101: spritesheet[4][17],
                      102: spritesheet[4][18],
                      103: spritesheet[4][19],
                      104: spritesheet[4][20]}

        try:
            with open(mapfile, 'r') as file:
                self.textmap = [[pygame.transform.scale2x(spritenums[int(y, 16)]) for y in x.split()] for x in file]
        except TypeError:
            self.textmap = [[spritenums[27] for y in range(mapfile[1])] for x in range(mapfile[0])]
